---
- name: Criando usuários no Linux
  hosts: linux
  gather_facts: yes

  tasks:
    - name: USER | Add user
      user: "{{ username }}"
        name: "{{ username }}"
        comment: "{{ comment }}"
        shell: "{{ shell }}"
        home: "{{ home }}"
        password: "{{ '{{ password }}' | password_hash('sha512', 'mysecrectsalt') }}"

        
        
        
...
