---
- name: Instalação de Pacotes
  hosts: linux
  gather_facts: yes

  tasks:
    - name: Instalando pacotes via YUM
      yum:
        name: "{{ packages }}" 
        state: latest
        #update_cache: yes
      when: ansible_distribution == "rocky" or ansible_distribution == "Redhat" or ansible_distribution == "ol"


...
